Vagrant.configure("2") do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true

    config.vm.define "grupo1-vm01" do |node|
        node.vm.hostname = "grupo1-vm01"
        node.vm.box = "centos/7"
        node.vm.provider "virtualbox" do |provider| 
            provider.memory = "1024"
            provider.cpus = "1"
        end
        node.vm.network "private_network", ip: "192.168.99.11"
        node.vm.provision "ansible" do |ansible|
            ansible.compatibility_mode = "2.0"
            ansible.playbook = "ansible-provision.yml"
        end
    end
end